### PR TITLE
Added command line flag parsing via cli package

### LINKED ISSUE #1: Help option
Hi, thanks for the nice tool.

Is a `lsp --help` or something in the pipeline? Where all the possible command-line options are shown?

### LINKED ISSUE #12: Create --help flag
LSP doesn't support either --help or --usage flags. This is a barrier to usability. Suggestion: for good command line flags using Go, I've used [this package](https://github.com/codegangsta/cli).

### PR DESCRIPTION
**Pull request by siddharthist**
Progress on #7
Fixes #12, fixes #1.

This is a great example of why you should use external libraries instead of falling trap to NIH.

### CODE REVIEW

**Comment by dborzov** [comment]
Nice! Thanks! 

You seem to have accidentally committed the executive binary for lsp. Could you clean that up?

**Comment by siddharthist** [comment]
Done, and put in .gitignore for future builds.

**Comment by siddharthist** [comment]
@dborzov Do you need anything else?

**Comment by dborzov** [comment]
@siddharthist sorry for the delay. PR looks great and is sorely needed! Thanks!

A couple of things:
* `lsp --help` prints out a nice help message but then the list of files is printed for the current directory right after it. It looks like this:
```sh
Incorrect Usage.

NAME:
   lsp - lsp is like ls command but more human-friendly

USAGE:
   lsp [global options] [arguments...]

VERSION:
   dev

AUTHOR(S):
   dborzov

GLOBAL OPTIONS:
   -d, --directories	Only show directories
   -h, --human		Show human readable file sizes
   -l, --long		Long form, show more details
   -s, --size		Show and order by size
   -t, --time		Show and order by modification time
   -p, --pyramid	Align files to the left side
   --version, -v	print the version

-------------------------------------------------------------------------------------------------
                                         fff333  dir(empty one)
                                    .travis.yml  Text File
                                     .gitignore  Text File
                                   arguments.go  Text File
                              arguments_test.go  Text File
                                CONTRIBUTING.md  Text File
                                         fmt.go  Text File
                                    fileinfo.go  Text File
                                    filelist.go  Text File
                                 investigate.go  Text File
                                        LICENSE  Text File
                                        main.go  Text File
                                       paths.go  Text File
                                      README.md  Text File
                                        sort.go  Text File
                                     tty_win.go  Text File
                                    traverse.go  Text File
                                        trie.go  Text File
                                    tty_unix.go  Text File
                                       utils.go  Text File
-------------------------------------------------------------------------------------------------
lsp "/k/src/github.com/dborzov/lsp", 21 files, 1 directories
               git repo (remote at git@github.com:dborzov/lsp.git)
```
It should only print the help message for `--help` key.
* Target directory argument should be mentioned in the help message. Currently
`lsp -s /k/src/github.com/dborzov/` is broken.
* I would not `lsp` into `.gitignore`. The binary file has been committed and then deleted in the next one, so it is still cached by git. Maybe rewrite history to just not commit the binary at all?
* Maybe put the documentation edits and `go fmt` some of the files in separate dedicated commits?
* I would delete `-d`, `-h`, `-l`, `-p` keys as they are not implemented anyway
* Plz delete `Author` and `Version` sections for `lsp --help`. I don't think anyone needs them.
I can add any of those changes myself if you prefer.

**Comment by siddharthist** [comment]
@dborzov I'd be happy to add some of them, I've just been a little busy. Feel free to add any yourself as well.

**Pull request closed without merging**
